//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class jboolean_ARRAY : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal jboolean_ARRAY(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(jboolean_ARRAY obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~jboolean_ARRAY() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          JNIPINVOKE.delete_jboolean_ARRAY(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public jboolean_ARRAY(int nelements) : this(JNIPINVOKE.new_jboolean_ARRAY(nelements), true) {
  }

  public byte getitem(int index) {
    byte ret = JNIPINVOKE.jboolean_ARRAY_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, byte value) {
    JNIPINVOKE.jboolean_ARRAY_setitem(swigCPtr, index, value);
  }

  public SWIGTYPE_p_unsigned_char cast() {
    global::System.IntPtr cPtr = JNIPINVOKE.jboolean_ARRAY_cast(swigCPtr);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public static jboolean_ARRAY frompointer(SWIGTYPE_p_unsigned_char t) {
    global::System.IntPtr cPtr = JNIPINVOKE.jboolean_ARRAY_frompointer(SWIGTYPE_p_unsigned_char.getCPtr(t));
    jboolean_ARRAY ret = (cPtr == global::System.IntPtr.Zero) ? null : new jboolean_ARRAY(cPtr, false);
    return ret;
  }

}
