//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class jdouble_ARRAY : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal jdouble_ARRAY(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(jdouble_ARRAY obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~jdouble_ARRAY() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          JNIPINVOKE.delete_jdouble_ARRAY(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public jdouble_ARRAY(int nelements) : this(JNIPINVOKE.new_jdouble_ARRAY(nelements), true) {
  }

  public double getitem(int index) {
    double ret = JNIPINVOKE.jdouble_ARRAY_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, double value) {
    JNIPINVOKE.jdouble_ARRAY_setitem(swigCPtr, index, value);
  }

  public SWIGTYPE_p_double cast() {
    global::System.IntPtr cPtr = JNIPINVOKE.jdouble_ARRAY_cast(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public static jdouble_ARRAY frompointer(SWIGTYPE_p_double t) {
    global::System.IntPtr cPtr = JNIPINVOKE.jdouble_ARRAY_frompointer(SWIGTYPE_p_double.getCPtr(t));
    jdouble_ARRAY ret = (cPtr == global::System.IntPtr.Zero) ? null : new jdouble_ARRAY(cPtr, false);
    return ret;
  }

}
