//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class jint_ARRAY : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal jint_ARRAY(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(jint_ARRAY obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~jint_ARRAY() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          JNIPINVOKE.delete_jint_ARRAY(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public jint_ARRAY(int nelements) : this(JNIPINVOKE.new_jint_ARRAY(nelements), true) {
  }

  public int getitem(int index) {
    int ret = JNIPINVOKE.jint_ARRAY_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, int value) {
    JNIPINVOKE.jint_ARRAY_setitem(swigCPtr, index, value);
  }

  public SWIGTYPE_p_long cast() {
    global::System.IntPtr cPtr = JNIPINVOKE.jint_ARRAY_cast(swigCPtr);
    SWIGTYPE_p_long ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_long(cPtr, false);
    return ret;
  }

  public static jint_ARRAY frompointer(SWIGTYPE_p_long t) {
    global::System.IntPtr cPtr = JNIPINVOKE.jint_ARRAY_frompointer(SWIGTYPE_p_long.getCPtr(t));
    jint_ARRAY ret = (cPtr == global::System.IntPtr.Zero) ? null : new jint_ARRAY(cPtr, false);
    return ret;
  }

}
