//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class jlong_ARRAY : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal jlong_ARRAY(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(jlong_ARRAY obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~jlong_ARRAY() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          JNIPINVOKE.delete_jlong_ARRAY(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public jlong_ARRAY(int nelements) : this(JNIPINVOKE.new_jlong_ARRAY(nelements), true) {
  }

  public long getitem(int index) {
    long ret = JNIPINVOKE.jlong_ARRAY_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, long value) {
    JNIPINVOKE.jlong_ARRAY_setitem(swigCPtr, index, value);
  }

  public SWIGTYPE_p___int64 cast() {
    global::System.IntPtr cPtr = JNIPINVOKE.jlong_ARRAY_cast(swigCPtr);
    SWIGTYPE_p___int64 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p___int64(cPtr, false);
    return ret;
  }

  public static jlong_ARRAY frompointer(SWIGTYPE_p___int64 t) {
    global::System.IntPtr cPtr = JNIPINVOKE.jlong_ARRAY_frompointer(SWIGTYPE_p___int64.getCPtr(t));
    jlong_ARRAY ret = (cPtr == global::System.IntPtr.Zero) ? null : new jlong_ARRAY(cPtr, false);
    return ret;
  }

}
