//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class JNI {
  public static byte GetValue(SWIGTYPE_p_unsigned_char elems, int index) {
    byte ret = JNIPINVOKE.GetValue(SWIGTYPE_p_unsigned_char.getCPtr(elems), index);
    return ret;
  }

  public static void SetValue(SWIGTYPE_p_unsigned_char elems, int index, byte value) {
    JNIPINVOKE.SetValue(SWIGTYPE_p_unsigned_char.getCPtr(elems), index, value);
  }

  public static int JNI_GetDefaultJavaVMInitArgs(SWIGTYPE_p_void args) {
    int ret = JNIPINVOKE.JNI_GetDefaultJavaVMInitArgs(SWIGTYPE_p_void.getCPtr(args));
    return ret;
  }

  public static int JNI_OnLoad(JavaVM vm, SWIGTYPE_p_void reserved) {
    int ret = JNIPINVOKE.JNI_OnLoad(JavaVM.getCPtr(vm), SWIGTYPE_p_void.getCPtr(reserved));
    return ret;
  }

  public static void JNI_OnUnload(JavaVM vm, SWIGTYPE_p_void reserved) {
    JNIPINVOKE.JNI_OnUnload(JavaVM.getCPtr(vm), SWIGTYPE_p_void.getCPtr(reserved));
  }

  public static readonly int JNI_FALSE = JNIPINVOKE.JNI_FALSE_get();
  public static readonly int JNI_TRUE = JNIPINVOKE.JNI_TRUE_get();
  public static readonly int JNI_OK = JNIPINVOKE.JNI_OK_get();
  public static readonly int JNI_ERR = JNIPINVOKE.JNI_ERR_get();
  public static readonly int JNI_EDETACHED = JNIPINVOKE.JNI_EDETACHED_get();
  public static readonly int JNI_EVERSION = JNIPINVOKE.JNI_EVERSION_get();
  public static readonly int JNI_ENOMEM = JNIPINVOKE.JNI_ENOMEM_get();
  public static readonly int JNI_EEXIST = JNIPINVOKE.JNI_EEXIST_get();
  public static readonly int JNI_EINVAL = JNIPINVOKE.JNI_EINVAL_get();
  public static readonly int JNI_COMMIT = JNIPINVOKE.JNI_COMMIT_get();
  public static readonly int JNI_ABORT = JNIPINVOKE.JNI_ABORT_get();
  public static readonly int JNI_VERSION_1_1 = JNIPINVOKE.JNI_VERSION_1_1_get();
  public static readonly int JNI_VERSION_1_2 = JNIPINVOKE.JNI_VERSION_1_2_get();
  public static readonly int JNI_VERSION_1_4 = JNIPINVOKE.JNI_VERSION_1_4_get();
  public static readonly int JNI_VERSION_1_6 = JNIPINVOKE.JNI_VERSION_1_6_get();
  public static readonly int JNI_VERSION_1_8 = JNIPINVOKE.JNI_VERSION_1_8_get();
}
