//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class JNIEnv : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal JNIEnv(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(JNIEnv obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~JNIEnv() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          JNIPINVOKE.delete_JNIEnv(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public void FUN() { }

  public int GetVersion() {
    int ret = JNIPINVOKE.JNIEnv_GetVersion(swigCPtr);
    return ret;
  }

  public unsafe JClass DefineClass(string name, JObject loader, sbyte[] buf, int len) {
    fixed ( sbyte* swig_ptrTo_buf = buf ) {
    {
      global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_DefineClass(swigCPtr, name, JObject.getCPtr(loader), (global::System.IntPtr)swig_ptrTo_buf, len);
      JClass ret = (cPtr == global::System.IntPtr.Zero) ? null : new JClass(cPtr, false);
      return ret;
    }
    }
  }

  public JClass FindClass(string name) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_FindClass(swigCPtr, name);
    JClass ret = (cPtr == global::System.IntPtr.Zero) ? null : new JClass(cPtr, false);
    return ret;
  }

  public  System.IntPtr  FromReflectedMethod(JObject method) {
        System.IntPtr ret = JNIPINVOKE.JNIEnv_FromReflectedMethod(swigCPtr, JObject.getCPtr(method));
        return ret;
    }

  public  System.IntPtr  FromReflectedField(JObject field) {
        System.IntPtr ret = JNIPINVOKE.JNIEnv_FromReflectedField(swigCPtr, JObject.getCPtr(field));
        return ret;
    }

  public JObject ToReflectedMethod(JClass cls,  System.IntPtr  methodID, byte isStatic) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_ToReflectedMethod(swigCPtr, JClass.getCPtr(cls),  methodID , isStatic);
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public JClass GetSuperclass(JClass sub) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetSuperclass(swigCPtr, JClass.getCPtr(sub));
    JClass ret = (cPtr == global::System.IntPtr.Zero) ? null : new JClass(cPtr, false);
    return ret;
  }

  public byte IsAssignableFrom(JClass sub, JClass sup) {
    byte ret = JNIPINVOKE.JNIEnv_IsAssignableFrom(swigCPtr, JClass.getCPtr(sub), JClass.getCPtr(sup));
    return ret;
  }

  public JObject ToReflectedField(JClass cls,  System.IntPtr  fieldID, byte isStatic) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_ToReflectedField(swigCPtr, JClass.getCPtr(cls),  fieldID , isStatic);
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public int Throw(JThrowable obj) {
    int ret = JNIPINVOKE.JNIEnv_Throw(swigCPtr, JThrowable.getCPtr(obj));
    return ret;
  }

  public int ThrowNew(JClass clazz, string msg) {
    int ret = JNIPINVOKE.JNIEnv_ThrowNew(swigCPtr, JClass.getCPtr(clazz), msg);
    return ret;
  }

  public JThrowable ExceptionOccurred() {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_ExceptionOccurred(swigCPtr);
    JThrowable ret = (cPtr == global::System.IntPtr.Zero) ? null : new JThrowable(cPtr, false);
    return ret;
  }

  public void ExceptionDescribe() {
    JNIPINVOKE.JNIEnv_ExceptionDescribe(swigCPtr);
  }

  public void ExceptionClear() {
    JNIPINVOKE.JNIEnv_ExceptionClear(swigCPtr);
  }

  public void FatalError(string msg) {
    JNIPINVOKE.JNIEnv_FatalError(swigCPtr, msg);
  }

  public int PushLocalFrame(int capacity) {
    int ret = JNIPINVOKE.JNIEnv_PushLocalFrame(swigCPtr, capacity);
    return ret;
  }

  public JObject PopLocalFrame(JObject result) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_PopLocalFrame(swigCPtr, JObject.getCPtr(result));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public JObject NewGlobalRef(JObject lobj) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewGlobalRef(swigCPtr, JObject.getCPtr(lobj));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public void DeleteGlobalRef(JObject gref) {
    JNIPINVOKE.JNIEnv_DeleteGlobalRef(swigCPtr, JObject.getCPtr(gref));
  }

  public void DeleteLocalRef(JObject obj) {
    JNIPINVOKE.JNIEnv_DeleteLocalRef(swigCPtr, JObject.getCPtr(obj));
  }

  public byte IsSameObject(JObject obj1, JObject obj2) {
    byte ret = JNIPINVOKE.JNIEnv_IsSameObject(swigCPtr, JObject.getCPtr(obj1), JObject.getCPtr(obj2));
    return ret;
  }

  public JObject NewLocalRef(JObject ref_) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewLocalRef(swigCPtr, JObject.getCPtr(ref_));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public int EnsureLocalCapacity(int capacity) {
    int ret = JNIPINVOKE.JNIEnv_EnsureLocalCapacity(swigCPtr, capacity);
    return ret;
  }

  public JObject AllocObject(JClass clazz) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_AllocObject(swigCPtr, JClass.getCPtr(clazz));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public JObject NewObject(JClass clazz,  System.IntPtr  methodID) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewObject(swigCPtr, JClass.getCPtr(clazz),  methodID );
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public JObject NewObjectV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewObjectV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public JObject NewObjectA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewObjectA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public JClass GetObjectClass(JObject obj) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetObjectClass(swigCPtr, JObject.getCPtr(obj));
    JClass ret = (cPtr == global::System.IntPtr.Zero) ? null : new JClass(cPtr, false);
    return ret;
  }

  public byte IsInstanceOf(JObject obj, JClass clazz) {
    byte ret = JNIPINVOKE.JNIEnv_IsInstanceOf(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz));
    return ret;
  }

  public  System.IntPtr  GetMethodID(JClass clazz, string name, string sig) {
        System.IntPtr ret = JNIPINVOKE.JNIEnv_GetMethodID(swigCPtr, JClass.getCPtr(clazz), name, sig);
        return ret;
    }

  public JObject CallObjectMethod(JObject obj,  System.IntPtr  methodID) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_CallObjectMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public JObject CallObjectMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_CallObjectMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public JObject CallObjectMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_CallObjectMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public byte CallBooleanMethod(JObject obj,  System.IntPtr  methodID) {
    byte ret = JNIPINVOKE.JNIEnv_CallBooleanMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
    return ret;
  }

  public byte CallBooleanMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    byte ret = JNIPINVOKE.JNIEnv_CallBooleanMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public byte CallBooleanMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    byte ret = JNIPINVOKE.JNIEnv_CallBooleanMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public sbyte CallByteMethod(JObject obj,  System.IntPtr  methodID) {
    sbyte ret = JNIPINVOKE.JNIEnv_CallByteMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
    return ret;
  }

  public sbyte CallByteMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    sbyte ret = JNIPINVOKE.JNIEnv_CallByteMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public sbyte CallByteMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    sbyte ret = JNIPINVOKE.JNIEnv_CallByteMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public ushort CallCharMethod(JObject obj,  System.IntPtr  methodID) {
    ushort ret = JNIPINVOKE.JNIEnv_CallCharMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
    return ret;
  }

  public ushort CallCharMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    ushort ret = JNIPINVOKE.JNIEnv_CallCharMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ushort CallCharMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    ushort ret = JNIPINVOKE.JNIEnv_CallCharMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public short CallShortMethod(JObject obj,  System.IntPtr  methodID) {
    short ret = JNIPINVOKE.JNIEnv_CallShortMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
    return ret;
  }

  public short CallShortMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    short ret = JNIPINVOKE.JNIEnv_CallShortMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public short CallShortMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    short ret = JNIPINVOKE.JNIEnv_CallShortMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public int CallIntMethod(JObject obj,  System.IntPtr  methodID) {
    int ret = JNIPINVOKE.JNIEnv_CallIntMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
    return ret;
  }

  public int CallIntMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    int ret = JNIPINVOKE.JNIEnv_CallIntMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int CallIntMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    int ret = JNIPINVOKE.JNIEnv_CallIntMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public long CallLongMethod(JObject obj,  System.IntPtr  methodID) {
    long ret = JNIPINVOKE.JNIEnv_CallLongMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
    return ret;
  }

  public long CallLongMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    long ret = JNIPINVOKE.JNIEnv_CallLongMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public long CallLongMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    long ret = JNIPINVOKE.JNIEnv_CallLongMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public float CallFloatMethod(JObject obj,  System.IntPtr  methodID) {
    float ret = JNIPINVOKE.JNIEnv_CallFloatMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
    return ret;
  }

  public float CallFloatMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    float ret = JNIPINVOKE.JNIEnv_CallFloatMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float CallFloatMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    float ret = JNIPINVOKE.JNIEnv_CallFloatMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public double CallDoubleMethod(JObject obj,  System.IntPtr  methodID) {
    double ret = JNIPINVOKE.JNIEnv_CallDoubleMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
    return ret;
  }

  public double CallDoubleMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    double ret = JNIPINVOKE.JNIEnv_CallDoubleMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double CallDoubleMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    double ret = JNIPINVOKE.JNIEnv_CallDoubleMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public void CallVoidMethod(JObject obj,  System.IntPtr  methodID) {
    JNIPINVOKE.JNIEnv_CallVoidMethod(swigCPtr, JObject.getCPtr(obj),  methodID );
  }

  public void CallVoidMethodV(JObject obj,  System.IntPtr  methodID, va_list args) {
    JNIPINVOKE.JNIEnv_CallVoidMethodV(swigCPtr, JObject.getCPtr(obj),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void CallVoidMethodA(JObject obj,  System.IntPtr  methodID, JValue args) {
    JNIPINVOKE.JNIEnv_CallVoidMethodA(swigCPtr, JObject.getCPtr(obj),  methodID , JValue.getCPtr(args));
  }

  public JObject CallNonvirtualObjectMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_CallNonvirtualObjectMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public JObject CallNonvirtualObjectMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_CallNonvirtualObjectMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public JObject CallNonvirtualObjectMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_CallNonvirtualObjectMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public byte CallNonvirtualBooleanMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    byte ret = JNIPINVOKE.JNIEnv_CallNonvirtualBooleanMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public byte CallNonvirtualBooleanMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    byte ret = JNIPINVOKE.JNIEnv_CallNonvirtualBooleanMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public byte CallNonvirtualBooleanMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    byte ret = JNIPINVOKE.JNIEnv_CallNonvirtualBooleanMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public sbyte CallNonvirtualByteMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    sbyte ret = JNIPINVOKE.JNIEnv_CallNonvirtualByteMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public sbyte CallNonvirtualByteMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    sbyte ret = JNIPINVOKE.JNIEnv_CallNonvirtualByteMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public sbyte CallNonvirtualByteMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    sbyte ret = JNIPINVOKE.JNIEnv_CallNonvirtualByteMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public ushort CallNonvirtualCharMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    ushort ret = JNIPINVOKE.JNIEnv_CallNonvirtualCharMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public ushort CallNonvirtualCharMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    ushort ret = JNIPINVOKE.JNIEnv_CallNonvirtualCharMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ushort CallNonvirtualCharMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    ushort ret = JNIPINVOKE.JNIEnv_CallNonvirtualCharMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public short CallNonvirtualShortMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    short ret = JNIPINVOKE.JNIEnv_CallNonvirtualShortMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public short CallNonvirtualShortMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    short ret = JNIPINVOKE.JNIEnv_CallNonvirtualShortMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public short CallNonvirtualShortMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    short ret = JNIPINVOKE.JNIEnv_CallNonvirtualShortMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public int CallNonvirtualIntMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    int ret = JNIPINVOKE.JNIEnv_CallNonvirtualIntMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public int CallNonvirtualIntMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    int ret = JNIPINVOKE.JNIEnv_CallNonvirtualIntMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int CallNonvirtualIntMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    int ret = JNIPINVOKE.JNIEnv_CallNonvirtualIntMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public long CallNonvirtualLongMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    long ret = JNIPINVOKE.JNIEnv_CallNonvirtualLongMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public long CallNonvirtualLongMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    long ret = JNIPINVOKE.JNIEnv_CallNonvirtualLongMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public long CallNonvirtualLongMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    long ret = JNIPINVOKE.JNIEnv_CallNonvirtualLongMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public float CallNonvirtualFloatMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    float ret = JNIPINVOKE.JNIEnv_CallNonvirtualFloatMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public float CallNonvirtualFloatMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    float ret = JNIPINVOKE.JNIEnv_CallNonvirtualFloatMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float CallNonvirtualFloatMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    float ret = JNIPINVOKE.JNIEnv_CallNonvirtualFloatMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public double CallNonvirtualDoubleMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    double ret = JNIPINVOKE.JNIEnv_CallNonvirtualDoubleMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public double CallNonvirtualDoubleMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    double ret = JNIPINVOKE.JNIEnv_CallNonvirtualDoubleMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double CallNonvirtualDoubleMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    double ret = JNIPINVOKE.JNIEnv_CallNonvirtualDoubleMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public void CallNonvirtualVoidMethod(JObject obj, JClass clazz,  System.IntPtr  methodID) {
    JNIPINVOKE.JNIEnv_CallNonvirtualVoidMethod(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID );
  }

  public void CallNonvirtualVoidMethodV(JObject obj, JClass clazz,  System.IntPtr  methodID, va_list args) {
    JNIPINVOKE.JNIEnv_CallNonvirtualVoidMethodV(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void CallNonvirtualVoidMethodA(JObject obj, JClass clazz,  System.IntPtr  methodID, JValue args) {
    JNIPINVOKE.JNIEnv_CallNonvirtualVoidMethodA(swigCPtr, JObject.getCPtr(obj), JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
  }

  public  System.IntPtr  GetFieldID(JClass clazz, string name, string sig) {
        System.IntPtr ret = JNIPINVOKE.JNIEnv_GetFieldID(swigCPtr, JClass.getCPtr(clazz), name, sig);
        return ret;
    }

  public JObject GetObjectField(JObject obj,  System.IntPtr  fieldID) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetObjectField(swigCPtr, JObject.getCPtr(obj),  fieldID );
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public byte GetBooleanField(JObject obj,  System.IntPtr  fieldID) {
    byte ret = JNIPINVOKE.JNIEnv_GetBooleanField(swigCPtr, JObject.getCPtr(obj),  fieldID );
    return ret;
  }

  public sbyte GetByteField(JObject obj,  System.IntPtr  fieldID) {
    sbyte ret = JNIPINVOKE.JNIEnv_GetByteField(swigCPtr, JObject.getCPtr(obj),  fieldID );
    return ret;
  }

  public ushort GetCharField(JObject obj,  System.IntPtr  fieldID) {
    ushort ret = JNIPINVOKE.JNIEnv_GetCharField(swigCPtr, JObject.getCPtr(obj),  fieldID );
    return ret;
  }

  public short GetShortField(JObject obj,  System.IntPtr  fieldID) {
    short ret = JNIPINVOKE.JNIEnv_GetShortField(swigCPtr, JObject.getCPtr(obj),  fieldID );
    return ret;
  }

  public int GetIntField(JObject obj,  System.IntPtr  fieldID) {
    int ret = JNIPINVOKE.JNIEnv_GetIntField(swigCPtr, JObject.getCPtr(obj),  fieldID );
    return ret;
  }

  public long GetLongField(JObject obj,  System.IntPtr  fieldID) {
    long ret = JNIPINVOKE.JNIEnv_GetLongField(swigCPtr, JObject.getCPtr(obj),  fieldID );
    return ret;
  }

  public float GetFloatField(JObject obj,  System.IntPtr  fieldID) {
    float ret = JNIPINVOKE.JNIEnv_GetFloatField(swigCPtr, JObject.getCPtr(obj),  fieldID );
    return ret;
  }

  public double GetDoubleField(JObject obj,  System.IntPtr  fieldID) {
    double ret = JNIPINVOKE.JNIEnv_GetDoubleField(swigCPtr, JObject.getCPtr(obj),  fieldID );
    return ret;
  }

  public void SetObjectField(JObject obj,  System.IntPtr  fieldID, JObject val) {
    JNIPINVOKE.JNIEnv_SetObjectField(swigCPtr, JObject.getCPtr(obj),  fieldID , JObject.getCPtr(val));
  }

  public void SetBooleanField(JObject obj,  System.IntPtr  fieldID, byte val) {
    JNIPINVOKE.JNIEnv_SetBooleanField(swigCPtr, JObject.getCPtr(obj),  fieldID , val);
  }

  public void SetByteField(JObject obj,  System.IntPtr  fieldID, sbyte val) {
    JNIPINVOKE.JNIEnv_SetByteField(swigCPtr, JObject.getCPtr(obj),  fieldID , val);
  }

  public void SetCharField(JObject obj,  System.IntPtr  fieldID, ushort val) {
    JNIPINVOKE.JNIEnv_SetCharField(swigCPtr, JObject.getCPtr(obj),  fieldID , val);
  }

  public void SetShortField(JObject obj,  System.IntPtr  fieldID, short val) {
    JNIPINVOKE.JNIEnv_SetShortField(swigCPtr, JObject.getCPtr(obj),  fieldID , val);
  }

  public void SetIntField(JObject obj,  System.IntPtr  fieldID, int val) {
    JNIPINVOKE.JNIEnv_SetIntField(swigCPtr, JObject.getCPtr(obj),  fieldID , val);
  }

  public void SetLongField(JObject obj,  System.IntPtr  fieldID, long val) {
    JNIPINVOKE.JNIEnv_SetLongField(swigCPtr, JObject.getCPtr(obj),  fieldID , val);
  }

  public void SetFloatField(JObject obj,  System.IntPtr  fieldID, float val) {
    JNIPINVOKE.JNIEnv_SetFloatField(swigCPtr, JObject.getCPtr(obj),  fieldID , val);
  }

  public void SetDoubleField(JObject obj,  System.IntPtr  fieldID, double val) {
    JNIPINVOKE.JNIEnv_SetDoubleField(swigCPtr, JObject.getCPtr(obj),  fieldID , val);
  }

  public  System.IntPtr  GetStaticMethodID(JClass clazz, string name, string sig) {
        System.IntPtr ret = JNIPINVOKE.JNIEnv_GetStaticMethodID(swigCPtr, JClass.getCPtr(clazz), name, sig);
        return ret;
    }

  public JObject CallStaticObjectMethod(JClass clazz,  System.IntPtr  methodID) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_CallStaticObjectMethod(swigCPtr, JClass.getCPtr(clazz),  methodID );
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public JObject CallStaticObjectMethodV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_CallStaticObjectMethodV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public JObject CallStaticObjectMethodA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_CallStaticObjectMethodA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public byte CallStaticBooleanMethod(JClass clazz,  System.IntPtr  methodID) {
    byte ret = JNIPINVOKE.JNIEnv_CallStaticBooleanMethod(swigCPtr, JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public byte CallStaticBooleanMethodV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    byte ret = JNIPINVOKE.JNIEnv_CallStaticBooleanMethodV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public byte CallStaticBooleanMethodA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    byte ret = JNIPINVOKE.JNIEnv_CallStaticBooleanMethodA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public sbyte CallStaticByteMethod(JClass clazz,  System.IntPtr  methodID) {
    sbyte ret = JNIPINVOKE.JNIEnv_CallStaticByteMethod(swigCPtr, JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public sbyte CallStaticByteMethodV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    sbyte ret = JNIPINVOKE.JNIEnv_CallStaticByteMethodV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public sbyte CallStaticByteMethodA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    sbyte ret = JNIPINVOKE.JNIEnv_CallStaticByteMethodA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public ushort CallStaticCharMethod(JClass clazz,  System.IntPtr  methodID) {
    ushort ret = JNIPINVOKE.JNIEnv_CallStaticCharMethod(swigCPtr, JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public ushort CallStaticCharMethodV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    ushort ret = JNIPINVOKE.JNIEnv_CallStaticCharMethodV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ushort CallStaticCharMethodA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    ushort ret = JNIPINVOKE.JNIEnv_CallStaticCharMethodA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public short CallStaticShortMethod(JClass clazz,  System.IntPtr  methodID) {
    short ret = JNIPINVOKE.JNIEnv_CallStaticShortMethod(swigCPtr, JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public short CallStaticShortMethodV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    short ret = JNIPINVOKE.JNIEnv_CallStaticShortMethodV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public short CallStaticShortMethodA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    short ret = JNIPINVOKE.JNIEnv_CallStaticShortMethodA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public int CallStaticIntMethod(JClass clazz,  System.IntPtr  methodID) {
    int ret = JNIPINVOKE.JNIEnv_CallStaticIntMethod(swigCPtr, JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public int CallStaticIntMethodV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    int ret = JNIPINVOKE.JNIEnv_CallStaticIntMethodV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int CallStaticIntMethodA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    int ret = JNIPINVOKE.JNIEnv_CallStaticIntMethodA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public long CallStaticLongMethod(JClass clazz,  System.IntPtr  methodID) {
    long ret = JNIPINVOKE.JNIEnv_CallStaticLongMethod(swigCPtr, JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public long CallStaticLongMethodV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    long ret = JNIPINVOKE.JNIEnv_CallStaticLongMethodV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public long CallStaticLongMethodA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    long ret = JNIPINVOKE.JNIEnv_CallStaticLongMethodA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public float CallStaticFloatMethod(JClass clazz,  System.IntPtr  methodID) {
    float ret = JNIPINVOKE.JNIEnv_CallStaticFloatMethod(swigCPtr, JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public float CallStaticFloatMethodV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    float ret = JNIPINVOKE.JNIEnv_CallStaticFloatMethodV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float CallStaticFloatMethodA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    float ret = JNIPINVOKE.JNIEnv_CallStaticFloatMethodA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public double CallStaticDoubleMethod(JClass clazz,  System.IntPtr  methodID) {
    double ret = JNIPINVOKE.JNIEnv_CallStaticDoubleMethod(swigCPtr, JClass.getCPtr(clazz),  methodID );
    return ret;
  }

  public double CallStaticDoubleMethodV(JClass clazz,  System.IntPtr  methodID, va_list args) {
    double ret = JNIPINVOKE.JNIEnv_CallStaticDoubleMethodV(swigCPtr, JClass.getCPtr(clazz),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double CallStaticDoubleMethodA(JClass clazz,  System.IntPtr  methodID, JValue args) {
    double ret = JNIPINVOKE.JNIEnv_CallStaticDoubleMethodA(swigCPtr, JClass.getCPtr(clazz),  methodID , JValue.getCPtr(args));
    return ret;
  }

  public void CallStaticVoidMethod(JClass cls,  System.IntPtr  methodID) {
    JNIPINVOKE.JNIEnv_CallStaticVoidMethod(swigCPtr, JClass.getCPtr(cls),  methodID );
  }

  public void CallStaticVoidMethodV(JClass cls,  System.IntPtr  methodID, va_list args) {
    JNIPINVOKE.JNIEnv_CallStaticVoidMethodV(swigCPtr, JClass.getCPtr(cls),  methodID , va_list.getCPtr(args));
    if (JNIPINVOKE.SWIGPendingException.Pending) throw JNIPINVOKE.SWIGPendingException.Retrieve();
  }

  public void CallStaticVoidMethodA(JClass cls,  System.IntPtr  methodID, JValue args) {
    JNIPINVOKE.JNIEnv_CallStaticVoidMethodA(swigCPtr, JClass.getCPtr(cls),  methodID , JValue.getCPtr(args));
  }

  public  System.IntPtr  GetStaticFieldID(JClass clazz, string name, string sig) {
        System.IntPtr ret = JNIPINVOKE.JNIEnv_GetStaticFieldID(swigCPtr, JClass.getCPtr(clazz), name, sig);
        return ret;
    }

  public JObject GetStaticObjectField(JClass clazz,  System.IntPtr  fieldID) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetStaticObjectField(swigCPtr, JClass.getCPtr(clazz),  fieldID );
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public byte GetStaticBooleanField(JClass clazz,  System.IntPtr  fieldID) {
    byte ret = JNIPINVOKE.JNIEnv_GetStaticBooleanField(swigCPtr, JClass.getCPtr(clazz),  fieldID );
    return ret;
  }

  public sbyte GetStaticByteField(JClass clazz,  System.IntPtr  fieldID) {
    sbyte ret = JNIPINVOKE.JNIEnv_GetStaticByteField(swigCPtr, JClass.getCPtr(clazz),  fieldID );
    return ret;
  }

  public ushort GetStaticCharField(JClass clazz,  System.IntPtr  fieldID) {
    ushort ret = JNIPINVOKE.JNIEnv_GetStaticCharField(swigCPtr, JClass.getCPtr(clazz),  fieldID );
    return ret;
  }

  public short GetStaticShortField(JClass clazz,  System.IntPtr  fieldID) {
    short ret = JNIPINVOKE.JNIEnv_GetStaticShortField(swigCPtr, JClass.getCPtr(clazz),  fieldID );
    return ret;
  }

  public int GetStaticIntField(JClass clazz,  System.IntPtr  fieldID) {
    int ret = JNIPINVOKE.JNIEnv_GetStaticIntField(swigCPtr, JClass.getCPtr(clazz),  fieldID );
    return ret;
  }

  public long GetStaticLongField(JClass clazz,  System.IntPtr  fieldID) {
    long ret = JNIPINVOKE.JNIEnv_GetStaticLongField(swigCPtr, JClass.getCPtr(clazz),  fieldID );
    return ret;
  }

  public float GetStaticFloatField(JClass clazz,  System.IntPtr  fieldID) {
    float ret = JNIPINVOKE.JNIEnv_GetStaticFloatField(swigCPtr, JClass.getCPtr(clazz),  fieldID );
    return ret;
  }

  public double GetStaticDoubleField(JClass clazz,  System.IntPtr  fieldID) {
    double ret = JNIPINVOKE.JNIEnv_GetStaticDoubleField(swigCPtr, JClass.getCPtr(clazz),  fieldID );
    return ret;
  }

  public void SetStaticObjectField(JClass clazz,  System.IntPtr  fieldID, JObject value) {
    JNIPINVOKE.JNIEnv_SetStaticObjectField(swigCPtr, JClass.getCPtr(clazz),  fieldID , JObject.getCPtr(value));
  }

  public void SetStaticBooleanField(JClass clazz,  System.IntPtr  fieldID, byte value) {
    JNIPINVOKE.JNIEnv_SetStaticBooleanField(swigCPtr, JClass.getCPtr(clazz),  fieldID , value);
  }

  public void SetStaticByteField(JClass clazz,  System.IntPtr  fieldID, sbyte value) {
    JNIPINVOKE.JNIEnv_SetStaticByteField(swigCPtr, JClass.getCPtr(clazz),  fieldID , value);
  }

  public void SetStaticCharField(JClass clazz,  System.IntPtr  fieldID, ushort value) {
    JNIPINVOKE.JNIEnv_SetStaticCharField(swigCPtr, JClass.getCPtr(clazz),  fieldID , value);
  }

  public void SetStaticShortField(JClass clazz,  System.IntPtr  fieldID, short value) {
    JNIPINVOKE.JNIEnv_SetStaticShortField(swigCPtr, JClass.getCPtr(clazz),  fieldID , value);
  }

  public void SetStaticIntField(JClass clazz,  System.IntPtr  fieldID, int value) {
    JNIPINVOKE.JNIEnv_SetStaticIntField(swigCPtr, JClass.getCPtr(clazz),  fieldID , value);
  }

  public void SetStaticLongField(JClass clazz,  System.IntPtr  fieldID, long value) {
    JNIPINVOKE.JNIEnv_SetStaticLongField(swigCPtr, JClass.getCPtr(clazz),  fieldID , value);
  }

  public void SetStaticFloatField(JClass clazz,  System.IntPtr  fieldID, float value) {
    JNIPINVOKE.JNIEnv_SetStaticFloatField(swigCPtr, JClass.getCPtr(clazz),  fieldID , value);
  }

  public void SetStaticDoubleField(JClass clazz,  System.IntPtr  fieldID, double value) {
    JNIPINVOKE.JNIEnv_SetStaticDoubleField(swigCPtr, JClass.getCPtr(clazz),  fieldID , value);
  }

  public JString NewString(SWIGTYPE_p_unsigned_short unicode, int len) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewString(swigCPtr, SWIGTYPE_p_unsigned_short.getCPtr(unicode), len);
    JString ret = (cPtr == global::System.IntPtr.Zero) ? null : new JString(cPtr, false);
    return ret;
  }

  public int GetStringLength(JString str) {
    int ret = JNIPINVOKE.JNIEnv_GetStringLength(swigCPtr, JString.getCPtr(str));
    return ret;
  }

  public SWIGTYPE_p_unsigned_short GetStringChars(JString str, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetStringChars(swigCPtr, JString.getCPtr(str), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
    return ret;
  }

  public void ReleaseStringChars(JString str, SWIGTYPE_p_unsigned_short chars) {
    JNIPINVOKE.JNIEnv_ReleaseStringChars(swigCPtr, JString.getCPtr(str), SWIGTYPE_p_unsigned_short.getCPtr(chars));
  }

  public JString NewStringUTF(string utf) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewStringUTF(swigCPtr, utf);
    JString ret = (cPtr == global::System.IntPtr.Zero) ? null : new JString(cPtr, false);
    return ret;
  }

  public int GetStringUTFLength(JString str) {
    int ret = JNIPINVOKE.JNIEnv_GetStringUTFLength(swigCPtr, JString.getCPtr(str));
    return ret;
  }

  public string GetStringUTFChars(JString str, SWIGTYPE_p_unsigned_char isCopy) {
    string ret = JNIPINVOKE.JNIEnv_GetStringUTFChars(swigCPtr, JString.getCPtr(str), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    return ret;
  }

  public void ReleaseStringUTFChars(JString str, string chars) {
    JNIPINVOKE.JNIEnv_ReleaseStringUTFChars(swigCPtr, JString.getCPtr(str), chars);
  }

  public int GetArrayLength(JArray array) {
    int ret = JNIPINVOKE.JNIEnv_GetArrayLength(swigCPtr, JArray.getCPtr(array));
    return ret;
  }

  public JObjectArray NewObjectArray(int len, JClass clazz, JObject init) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewObjectArray(swigCPtr, len, JClass.getCPtr(clazz), JObject.getCPtr(init));
    JObjectArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObjectArray(cPtr, false);
    return ret;
  }

  public JObject GetObjectArrayElement(JObjectArray array, int index) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetObjectArrayElement(swigCPtr, JObjectArray.getCPtr(array), index);
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public void SetObjectArrayElement(JObjectArray array, int index, JObject val) {
    JNIPINVOKE.JNIEnv_SetObjectArrayElement(swigCPtr, JObjectArray.getCPtr(array), index, JObject.getCPtr(val));
  }

  public JBooleanArray NewBooleanArray(int len) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewBooleanArray(swigCPtr, len);
    JBooleanArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new JBooleanArray(cPtr, false);
    return ret;
  }

  public JByteArray NewByteArray(int len) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewByteArray(swigCPtr, len);
    JByteArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new JByteArray(cPtr, false);
    return ret;
  }

  public JCharArray NewCharArray(int len) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewCharArray(swigCPtr, len);
    JCharArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new JCharArray(cPtr, false);
    return ret;
  }

  public JShortArray NewShortArray(int len) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewShortArray(swigCPtr, len);
    JShortArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new JShortArray(cPtr, false);
    return ret;
  }

  public JIntArray NewIntArray(int len) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewIntArray(swigCPtr, len);
    JIntArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new JIntArray(cPtr, false);
    return ret;
  }

  public JLongArray NewLongArray(int len) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewLongArray(swigCPtr, len);
    JLongArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new JLongArray(cPtr, false);
    return ret;
  }

  public JFloatArray NewFloatArray(int len) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewFloatArray(swigCPtr, len);
    JFloatArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new JFloatArray(cPtr, false);
    return ret;
  }

  public JDoubleArray NewDoubleArray(int len) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewDoubleArray(swigCPtr, len);
    JDoubleArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new JDoubleArray(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_unsigned_char GetBooleanArrayElements(JBooleanArray array, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetBooleanArrayElements(swigCPtr, JBooleanArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_signed_char GetByteArrayElements(JByteArray array, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetByteArrayElements(swigCPtr, JByteArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_signed_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_signed_char(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_unsigned_short GetCharArrayElements(JCharArray array, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetCharArrayElements(swigCPtr, JCharArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_short GetShortArrayElements(JShortArray array, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetShortArrayElements(swigCPtr, JShortArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_short(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_long GetIntArrayElements(JIntArray array, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetIntArrayElements(swigCPtr, JIntArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_long ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_long(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p___int64 GetLongArrayElements(JLongArray array, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetLongArrayElements(swigCPtr, JLongArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p___int64 ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p___int64(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_float GetFloatArrayElements(JFloatArray array, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetFloatArrayElements(swigCPtr, JFloatArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_double GetDoubleArrayElements(JDoubleArray array, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetDoubleArrayElements(swigCPtr, JDoubleArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public void ReleaseBooleanArrayElements(JBooleanArray array, SWIGTYPE_p_unsigned_char elems, int mode) {
    JNIPINVOKE.JNIEnv_ReleaseBooleanArrayElements(swigCPtr, JBooleanArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(elems), mode);
  }

  public void ReleaseByteArrayElements(JByteArray array, SWIGTYPE_p_signed_char elems, int mode) {
    JNIPINVOKE.JNIEnv_ReleaseByteArrayElements(swigCPtr, JByteArray.getCPtr(array), SWIGTYPE_p_signed_char.getCPtr(elems), mode);
  }

  public void ReleaseCharArrayElements(JCharArray array, SWIGTYPE_p_unsigned_short elems, int mode) {
    JNIPINVOKE.JNIEnv_ReleaseCharArrayElements(swigCPtr, JCharArray.getCPtr(array), SWIGTYPE_p_unsigned_short.getCPtr(elems), mode);
  }

  public void ReleaseShortArrayElements(JShortArray array, SWIGTYPE_p_short elems, int mode) {
    JNIPINVOKE.JNIEnv_ReleaseShortArrayElements(swigCPtr, JShortArray.getCPtr(array), SWIGTYPE_p_short.getCPtr(elems), mode);
  }

  public void ReleaseIntArrayElements(JIntArray array, SWIGTYPE_p_long elems, int mode) {
    JNIPINVOKE.JNIEnv_ReleaseIntArrayElements(swigCPtr, JIntArray.getCPtr(array), SWIGTYPE_p_long.getCPtr(elems), mode);
  }

  public void ReleaseLongArrayElements(JLongArray array, SWIGTYPE_p___int64 elems, int mode) {
    JNIPINVOKE.JNIEnv_ReleaseLongArrayElements(swigCPtr, JLongArray.getCPtr(array), SWIGTYPE_p___int64.getCPtr(elems), mode);
  }

  public void ReleaseFloatArrayElements(JFloatArray array, SWIGTYPE_p_float elems, int mode) {
    JNIPINVOKE.JNIEnv_ReleaseFloatArrayElements(swigCPtr, JFloatArray.getCPtr(array), SWIGTYPE_p_float.getCPtr(elems), mode);
  }

  public void ReleaseDoubleArrayElements(JDoubleArray array, SWIGTYPE_p_double elems, int mode) {
    JNIPINVOKE.JNIEnv_ReleaseDoubleArrayElements(swigCPtr, JDoubleArray.getCPtr(array), SWIGTYPE_p_double.getCPtr(elems), mode);
  }

  public void GetBooleanArrayRegion(JBooleanArray array, int start, int len, byte[] buf) {
    fixed ( byte* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_GetBooleanArrayRegion(swigCPtr, JBooleanArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void GetByteArrayRegion(JByteArray array, int start, int len, sbyte[] buf) {
    fixed ( sbyte* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_GetByteArrayRegion(swigCPtr, JByteArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void GetCharArrayRegion(JCharArray array, int start, int len, ushort[] buf) {
    fixed ( ushort* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_GetCharArrayRegion(swigCPtr, JCharArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void GetShortArrayRegion(JShortArray array, int start, int len, short[] buf) {
    fixed ( short* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_GetShortArrayRegion(swigCPtr, JShortArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void GetIntArrayRegion(JIntArray array, int start, int len, int[] buf) {
    fixed ( int* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_GetIntArrayRegion(swigCPtr, JIntArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void GetLongArrayRegion(JLongArray array, int start, int len, jlong[] buf) {
    fixed ( jlong* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_GetLongArrayRegion(swigCPtr, JLongArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void GetFloatArrayRegion(JFloatArray array, int start, int len, float[] buf) {
    fixed ( float* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_GetFloatArrayRegion(swigCPtr, JFloatArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void GetDoubleArrayRegion(JDoubleArray array, int start, int len, double[] buf) {
    fixed ( double* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_GetDoubleArrayRegion(swigCPtr, JDoubleArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void SetBooleanArrayRegion(JBooleanArray array, int start, int len, byte[] buf) {
    fixed ( byte* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_SetBooleanArrayRegion(swigCPtr, JBooleanArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void SetByteArrayRegion(JByteArray array, int start, int len, sbyte[] buf) {
    fixed ( sbyte* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_SetByteArrayRegion(swigCPtr, JByteArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void SetCharArrayRegion(JCharArray array, int start, int len, ushort[] buf) {
    fixed ( ushort* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_SetCharArrayRegion(swigCPtr, JCharArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void SetShortArrayRegion(JShortArray array, int start, int len, short[] buf) {
    fixed ( short* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_SetShortArrayRegion(swigCPtr, JShortArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void SetIntArrayRegion(JIntArray array, int start, int len, int[] buf) {
    fixed ( int* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_SetIntArrayRegion(swigCPtr, JIntArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void SetLongArrayRegion(JLongArray array, int start, int len, jlong[] buf) {
    fixed ( jlong* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_SetLongArrayRegion(swigCPtr, JLongArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void SetFloatArrayRegion(JFloatArray array, int start, int len, float[] buf) {
    fixed ( float* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_SetFloatArrayRegion(swigCPtr, JFloatArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void SetDoubleArrayRegion(JDoubleArray array, int start, int len, double[] buf) {
    fixed ( double* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_SetDoubleArrayRegion(swigCPtr, JDoubleArray.getCPtr(array), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public int RegisterNatives(JClass clazz, JNINativeMethod methods, int nMethods) {
    int ret = JNIPINVOKE.JNIEnv_RegisterNatives(swigCPtr, JClass.getCPtr(clazz), JNINativeMethod.getCPtr(methods), nMethods);
    return ret;
  }

  public int UnregisterNatives(JClass clazz) {
    int ret = JNIPINVOKE.JNIEnv_UnregisterNatives(swigCPtr, JClass.getCPtr(clazz));
    return ret;
  }

  public int MonitorEnter(JObject obj) {
    int ret = JNIPINVOKE.JNIEnv_MonitorEnter(swigCPtr, JObject.getCPtr(obj));
    return ret;
  }

  public int MonitorExit(JObject obj) {
    int ret = JNIPINVOKE.JNIEnv_MonitorExit(swigCPtr, JObject.getCPtr(obj));
    return ret;
  }

  public void GetStringRegion(JString str, int start, int len, ushort[] buf) {
    fixed ( ushort* swig_ptrTo_buf = buf ) {
    {
      JNIPINVOKE.JNIEnv_GetStringRegion(swigCPtr, JString.getCPtr(str), start, len, (global::System.IntPtr)swig_ptrTo_buf);
    }
    }
  }

  public void GetStringUTFRegion(JString str, int start, int len, string buf) {
    JNIPINVOKE.JNIEnv_GetStringUTFRegion(swigCPtr, JString.getCPtr(str), start, len, buf);
  }

  public SWIGTYPE_p_void GetPrimitiveArrayCritical(JArray array, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetPrimitiveArrayCritical(swigCPtr, JArray.getCPtr(array), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public void ReleasePrimitiveArrayCritical(JArray array, SWIGTYPE_p_void carray, int mode) {
    JNIPINVOKE.JNIEnv_ReleasePrimitiveArrayCritical(swigCPtr, JArray.getCPtr(array), SWIGTYPE_p_void.getCPtr(carray), mode);
  }

  public SWIGTYPE_p_unsigned_short GetStringCritical(JString string_, SWIGTYPE_p_unsigned_char isCopy) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetStringCritical(swigCPtr, JString.getCPtr(string_), SWIGTYPE_p_unsigned_char.getCPtr(isCopy));
    SWIGTYPE_p_unsigned_short ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
    return ret;
  }

  public void ReleaseStringCritical(JString string_, SWIGTYPE_p_unsigned_short cstring) {
    JNIPINVOKE.JNIEnv_ReleaseStringCritical(swigCPtr, JString.getCPtr(string_), SWIGTYPE_p_unsigned_short.getCPtr(cstring));
  }

  public JObject NewWeakGlobalRef(JObject obj) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewWeakGlobalRef(swigCPtr, JObject.getCPtr(obj));
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public void DeleteWeakGlobalRef(JObject ref_) {
    JNIPINVOKE.JNIEnv_DeleteWeakGlobalRef(swigCPtr, JObject.getCPtr(ref_));
  }

  public byte ExceptionCheck() {
    byte ret = JNIPINVOKE.JNIEnv_ExceptionCheck(swigCPtr);
    return ret;
  }

  public JObject NewDirectByteBuffer(SWIGTYPE_p_void address, long capacity) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_NewDirectByteBuffer(swigCPtr, SWIGTYPE_p_void.getCPtr(address), capacity);
    JObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new JObject(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_void GetDirectBufferAddress(JObject buf) {
    global::System.IntPtr cPtr = JNIPINVOKE.JNIEnv_GetDirectBufferAddress(swigCPtr, JObject.getCPtr(buf));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public long GetDirectBufferCapacity(JObject buf) {
    long ret = JNIPINVOKE.JNIEnv_GetDirectBufferCapacity(swigCPtr, JObject.getCPtr(buf));
    return ret;
  }

  public JObjectRefType GetObjectRefType(JObject obj) {
    JObjectRefType ret = (JObjectRefType)JNIPINVOKE.JNIEnv_GetObjectRefType(swigCPtr, JObject.getCPtr(obj));
    return ret;
  }

  public JNIEnv() : this(JNIPINVOKE.new_JNIEnv(), true) {
  }

}
